### ISSUE TITLE
Is there an alignement across all languages (or some) for same meanings ?

### ISSUE THREAD

**Issue by ghost** [elexis-eu/MWSA#1]
Hi,
Thanks a lot for providing this,
I'm trying to build a very simple word to word translator.

Is there shared ID between each lemma in different languages corporas? Even if poor alignment it is fine.

Like same ID for ("cat", english) and ("kat", german)

Thanks a lot

**Comment by sinaahmadi** [comment]
Hi @bacloud22,
Thanks for your message. Unfortunately, that is not possible across languages. It would be a nice idea to do though by first, aligning at the word level and then sense level.

Check out TIAD if you are interested in translation inference: https://tiad2021.unizar.es/index.html

**Comment by ghost** [comment]
Thanks it looks promising.
